export const data = [
    {
        id: 1,
        nameProduct: "Bajo Squier classic vibe 70's color madera",
        price: 12000,
        urlImage: "https://marikomusic.com.mx/wp-content/uploads/2022/05/Bajo_Electrico_Classic_Vibe-_70s_Squier_Fender_Natural_0374550521_1-1.jpg",
        quantity: 1,
    },
    {
        id: 2,
        nameProduct: "Bajo Squier classic vibe 70's Negro",
        price: 11500,
        urlImage: "https://www.mrcdinstrumentos.com.mx/shared/productos/19397/0374550506.jpg",
        quantity: 1,
    },
    {
        id: 3,
        nameProduct: "Bajo Squier Jazz Bass 5 cuerdas blanco",
        price: 9000,
        urlImage: "https://gamamusic.com/cdn/shop/files/0378652505-3.jpg?v=1694645292&width=800",
        quantity: 1,
    },
    {
        id: 4,
        nameProduct: "Bajo Yamaha TRBX305 5 cuerdas rojo",
        price: 9690,
        urlImage: "https://marikomusic.com.mx/wp-content/uploads/2023/01/Bajo-Electrico-5-Cuerdas-Yamaha-TRBX305-Candy-Apple-Red.jpg",
        quantity: 1,
    },
    {
        id: 5,
        nameProduct: "Bajo Yamaha TRBX305 5 cuerdas negro",
        price: 9690,
        urlImage: "https://www.tiendasonomusic.com/cdn/shop/products/imagen_2021-05-10_164955@2x.png?v=1620683681",
        quantity: 1,
    },
    {
        id: 6,
        nameProduct: "Bajo Yamaha TRBX305 5 cuerdas blanco",
        price: 10200,
        urlImage: "https://accordionproshop.com/cdn/shop/files/Yamaha-TRBX305-WH-300-Series-5-String-Electric-Bass-White-bass-www_hermesmusic_com_800x.jpg?v=1716488682",
        quantity: 1,
    },
    {
        id: 7,
        nameProduct: "Bajo Yamaha TRBX605 5 cuerdas marrón",
        price: 18899,
        urlImage: "https://resources.sanborns.com.mx/imagenes-sanborns-ii/1200/4957812537322.jpg?scale=500&qlty=75",
        quantity: 1,
    },
    {
        id: 8,
        nameProduct: "Bajo Yamaha TRBX605 5 cuerdas madera",
        price: 17500,
        urlImage: "https://resources.sears.com.mx/medios-plazavip/s2/14117/2244316/60400b941f12a-preview-1600x1600.jpg?scale=500&qlty=75",
        quantity: 1,
    },
    {
        id: 9,
        nameProduct: "Epiphone UpTown Kat azul",
        price: 17300,
        urlImage: "https://www.mrcdinstrumentos.com.mx/shared/productos/21436/ETUESBMNH1-01.jpg",
        quantity: 1,
    },
    {
        id: 10,
        nameProduct: "Epiphone UpTown Kat roja",
        price: 16000,
        urlImage: "https://www.mrcdinstrumentos.com.mx/shared/productos/21435/ETUERUMGH1-01.jpg",
        quantity: 1,
    },
    {
        id: 11,
        nameProduct: "Epiphone UpTown Kat verde",
        price: 17200,
        urlImage: "https://ss631.liverpool.com.mx/xl/1129510583.jpg",
        quantity: 1,
    },
    {
        id: 12,
        nameProduct: "Epiphone Emperor Swingster color azul",
        price: 16000,
        urlImage: "https://guitardepotmx.com/cdn/shop/products/ETS2DBMNB1_front_r5rg-xq.jpg?v=1671648295",
        quantity: 1,
    },
    {
        id: 13,
        nameProduct: "Epiphone Emperor Swingster color verde",
        price: 17500,
        urlImage: "https://www.mrcdinstrumentos.com.mx/shared/productos/26224/ETS2FGMGB1-01.jpg",
        quantity: 1,
    },
    {
        id: 14,
        nameProduct: "Epiphone Emperor Swingster color negro",
        price: 16200,
        urlImage: "https://r2.gear4music.com/media/91/919011/600/preview.jpg",
        quantity: 1,
    },
    {
        id: 15,
        nameProduct: "Guitarra Electroacustica Fender CD-60SCE Natural",
        price: 5150,
        urlImage: "https://www.falymusic.com/images/detailed/10/4.jpg",
        quantity: 1,
    },
    {
        id: 16,
        nameProduct: "Guitarra Electroacustica Fender Cd-140sce",
        price: 4800,
        urlImage: "https://www.falymusic.com/images/detailed/20/0970213321_gtr_frt_001_rr.jpg",
        quantity: 1,
    },
    {
        id: 17,
        nameProduct: "Guitarra Electro-acustica Epiphone Natural",
        price: 7999,
        urlImage: "https://www.falymusic.com/images/detailed/21/P_AJ210CE-NA1_opt__1_.jpg",
        quantity: 1,
    },
    {
        id: 18,
        nameProduct: "Novation UltraNova Nova Series analogue-modeling sintetizador",
        price: 10829,
        urlImage: "https://sintetizadoresmexico.com/cdn/shop/products/10353987_800.jpg?v=1604480592",
        quantity: 1,
    },
    {
        id: 19,
        nameProduct: "Nord Stage",
        price: 122269,
        urlImage: "https://m.media-amazon.com/images/I/61l6xcnET1L._AC_SL1200_.jpg",
        quantity: 1,
    },
    {
        id: 20,
        nameProduct: "Controlador AKAI Professional MPK249",
        price: 6680,
        urlImage: "https://m.media-amazon.com/images/I/610FH7FxlFL._AC_SL1200_.jpg",
        quantity: 1,
    },
    {
        id: 21,
        nameProduct: "Controlador AKAI Professional MPK261",
        price: 8532,
        urlImage: "https://m.media-amazon.com/images/I/61LSNnVDkjL._AC_SL1175_.jpg",
        quantity: 1,
    },
    {
        id: 22,
        nameProduct: "Controlador AKAI Professional MPK225",
        price: 6133,
        urlImage: "https://m.media-amazon.com/images/I/61X7L1KqCKL._AC_SL1276_.jpg",
        quantity: 1,
    },
    {
        id: 23,
        nameProduct: "Controlador AKAI Professional MPK Mini Plus",
        price: 3999,
        urlImage: "https://m.media-amazon.com/images/I/71wM4lMm+qL._AC_SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 24,
        nameProduct: "Guitarra eléctrica squier Stratocaster Negro con blanco",
        price: 4399,
        urlImage: "https://www.jpmusical.com/cdn/shop/products/SQUIER_1_d2bb25dd-18bc-4858-9f00-018916dcf254.png?v=1660084103",
        quantity: 1,
    },
    {
        id: 25,
        nameProduct: "Guitarra eléctrica squier Stratocaster blanca",
        price: 5808,
        urlImage: "https://www.musicalesdoris.com/cdn/shop/products/1b30e40d6c7f0bb71546c7cb9d4296fb-guitarra-electrica-fender-squier-sonic-strat-ht-mn-wpg-0373252580_1280x.png?v=1683573896",
        quantity: 1,
    },
    {
        id: 26,
        nameProduct: "Guitarra eléctrica Gretsch G2420T Streamliner",
        price: 13460,
        urlImage: "https://m.media-amazon.com/images/I/61gCnBw9YWL._AC_SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 27,
        nameProduct: "Batería Alesis Nitro Mesh Kit",
        price: 8999,
        urlImage: "https://m.media-amazon.com/images/I/711x2SNFTpL._AC_SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 28,
        nameProduct: "Batería Alesis Nitro Max Kit",
        price: 9999,
        urlImage: "https://m.media-amazon.com/images/I/71FgF8gIBvL._AC_SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 29,
        nameProduct: "Batería Alesis Turbo Mesh Kit",
        price: 7062,
        urlImage: "https://m.media-amazon.com/images/I/71DNgefy83L._AC_SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 30,
        nameProduct: "Batería Alesis Surge Mesh Kit",
        price: 13696,
        urlImage: "https://m.media-amazon.com/images/I/71vJAaBoT-L._AC_SL1500_.jpg",
        quantity: 1,
    },
        
]